# Specify a base image
# Use node as base image
# because normal alpine doesn't preinstall npm
# Specify :alpine not to install too much programms
FROM node:alpine

WORKDIR /usr/app

COPY ./ ./
# Install some dependencies
RUN npm install

# Default command
CMD ["npm", "start"]